# Logging
project_name: udl
logger: local
# Model Class (S, L, M)
model: M
positive_freqs: False

# Network
in_features: 2
out_features: 3
hidden_layers: 1
hidden_features: [32, 64, 128, 192, 256]
bias: True
max_stages: 5

pmode: wrap
domain: [-1, 1]
# mask_color: 130

# Frequency Initialization
omega_0: [3, 4, 12, 20, 48]
hidden_omega_0: 30
superposition_w0: True

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0', 'd1']

# Loss
loss_function: 'mse'
loss_weights: {'d0': 1, 'd1': 0.0}
optim_handler: 'regular'

# Training
opt_method: Adam
lr: 0.0001
loss_tol: 0.00000000001
diff_tol: 0.0000001
max_epochs_per_stage: 1000
batch_size: 256 * 128

# Image
data_path: ../data/masp.jpg
width: 256
height: 256
channels: 3
#see: https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-modes
color_space: RGB

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cuda

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-2, 2]
zoom: [2, 4]
zoom_filters: ['linear', 'cubic', 'nearest']